version: "3.7"

services:
  webapp:
    image:
    environment:
      - MONGO_URL=mongodb://mongo:27017/dev
    depends_on:
      - mongo
    ports:
      - "8080: 8080"
    networks:
      - network-frontend

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    networks:
      - network-backend

networks:
  network-backend:
  network-frontend:
